# Generated by Django 4.0.2 on 2022-03-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftbox', '0002_alter_link_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(blank=True, to='craftbox.Tag'),
        ),
    ]
